<a href="https://colab.research.google.com/github/nojiyoon/SeSAC_code/blob/main/3_1_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_1_x_%EB%A5%BC_%EC%9D%B4%EC%9A%A9%ED%95%9C_%EC%84%A0%ED%98%95_%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensorflow 1.x: 아래 두가지만 도와줌

- 기울기 계산
- w, b 업데이트

Tensorflow 2.x : 무지 많이 도와줌
(= keras)

In [44]:
%tensorflow_version 1.x

In [45]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [46]:
tf.enable_eager_execution()
tf.__version__

'1.15.2'

In [47]:
X = np.array([1, 2, 3], dtype="float32")
Y = np.array([2, 2.5, 3.5], dtype="float32")

In [48]:
W = tf.Variable([2], dtype="float32")
b = tf.Variable([1], dtype="float32")

In [49]:
W

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.], dtype=float32)>

In [50]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>

- tensorflow는 기본적으로 W, b 값을 출력 불가!
- W, b 값 출력 하고싶다면 맨 처음에 tf.enable_eager_execution() 선언해야됨

In [51]:
learning_rate = 0.1

In [52]:
hypothesis = W * X + b
print("hypothesis:", hypothesis)    # 예측값

print("hypothesis - y:", (hypothesis - Y))  # 예측값 - 진짜값

hypothesis: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
hypothesis - y: tf.Tensor([1.  2.5 3.5], shape=(3,), dtype=float32)


In [53]:
hypothesis = W * X + b
print("hypothesis:", hypothesis)    # 예측값

print("hypothesis - y:", (hypothesis - Y))  # 예측값 - 진짜값
print("tf.square(hypothesis - Y):", tf.square(hypothesis - Y)) # (예측값 - 진짜값)의 제곱

hypothesis: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
hypothesis - y: tf.Tensor([1.  2.5 3.5], shape=(3,), dtype=float32)
tf.square(hypothesis - Y): tf.Tensor([ 1.    6.25 12.25], shape=(3,), dtype=float32)


In [54]:
hypothesis = W * X + b
print("hypothesis:", hypothesis)    # 예측값

print("hypothesis - y:", (hypothesis - Y))  # 예측값 - 진짜값
print("tf.square(hypothesis - Y):", tf.square(hypothesis - Y)) # (예측값 - 진짜값)의 제곱
print("tf.reduce_mean(tf.square(hypothesis - Y)):", tf.reduce_mean(tf.square(hypothesis - Y))) # (예측값 - 진짜값)의 평균

hypothesis: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
hypothesis - y: tf.Tensor([1.  2.5 3.5], shape=(3,), dtype=float32)
tf.square(hypothesis - Y): tf.Tensor([ 1.    6.25 12.25], shape=(3,), dtype=float32)
tf.reduce_mean(tf.square(hypothesis - Y)): tf.Tensor(6.5, shape=(), dtype=float32)


In [55]:
hypothesis = W * X + b
print("hypothesis:", hypothesis)    # 예측값

# print("hypothesis - y:", (hypothesis - Y))  # 예측값 - 진짜값
# print("tf.square(hypothesis - Y):", tf.square(hypothesis - Y)) # (예측값 - 진짜값)의 제곱
# print("tf.reduce_mean(hypothesis - Y):", tf.reduce_mean(hypothesis - Y)) # (예측값 - 진짜값)의 평균

cost = tf.reduce_mean( tf.square(hypothesis - Y) )
print("cost = ", cost)

hypothesis: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
cost =  tf.Tensor(6.5, shape=(), dtype=float32)


In [56]:
hypothesis = W * X + b
print("hypothesis:", hypothesis)    # 예측값

cost = tf.reduce_mean( tf.square(hypothesis - Y) )
print("cost = ", cost)
tape = tf.GradientTape()

W_grad, b_grad = tape.gradient(cost, [W, b])
print("W_grad", W_grad, ', b_grad', b_grad)

hypothesis: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
cost =  tf.Tensor(6.5, shape=(), dtype=float32)


RuntimeError: ignored

In [57]:
hypothesis = W * X + b
print("hypothesis:", hypothesis)    # 예측값

cost = tf.reduce_mean( tf.square(hypothesis - Y) )
print("cost = ", cost)

# tape = tf.GradientTape()  # <- 에러남
with tf.GradientTape() as tape:
  pass

W_grad, b_grad = tape.gradient(cost, [W, b])
print("W_grad", W_grad, ', b_grad', b_grad)

hypothesis: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
cost =  tf.Tensor(6.5, shape=(), dtype=float32)
W_grad None , b_grad None


- 에러는 안 나지만 기울기 계산 안됨

In [58]:
with tf.GradientTape() as tape:

  hypothesis = W * X + b
  print("hypothesis:", hypothesis)    # 예측값

  cost = tf.reduce_mean( tf.square(hypothesis - Y) )
  print("cost = ", cost)

W_grad, b_grad = tape.gradient(cost, [W, b])
print("W_grad", W_grad, ', b_grad', b_grad)

hypothesis: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
cost =  tf.Tensor(6.5, shape=(), dtype=float32)
W_grad tf.Tensor([11.], shape=(1,), dtype=float32) , b_grad tf.Tensor([4.666667], shape=(1,), dtype=float32)


- tape가 맨 처음에 나오고 그 안에 hypothesis, cost가 있어야 됨

In [59]:
with tf.GradientTape() as tape:
  hypothesis = W * X + b
  print("hypothesis:", hypothesis)
  cost = tf.reduce_mean(tf.square(hypothesis - Y))
  print("cost:", cost)

W_grad, b_grad = tape.gradient(cost, [W, b])
print("W_grad:", W_grad, ", b_grad:", b_grad)

W.assign_sub(W_grad * learning_rate)
b.assign_sub(b_grad * learning_rate)

hypothesis: tf.Tensor([3. 5. 7.], shape=(3,), dtype=float32)
cost: tf.Tensor(6.5, shape=(), dtype=float32)
W_grad: tf.Tensor([11.], shape=(1,), dtype=float32) , b_grad: tf.Tensor([4.666667], shape=(1,), dtype=float32)


<tf.Variable 'UnreadVariable' shape=(1,) dtype=float32, numpy=array([0.5333333], dtype=float32)>

In [15]:
# 반복해서 W, b를 업데이트
for i in range(1000):
  # 기울기 계산할 객체
  # 프로그램 끝까지 살아있음
  with tf.GradientTape() as tape:
    hypothesis = W * X + b
    print("hypothesis:", hypothesis)
    cost = tf.reduce_mean(tf.square(hypothesis - Y))
    print("cost:", cost)

  W_grad, b_grad = tape.gradient(cost, [W, b])
  print("W_grad:", W_grad, ", b_grad:", b_grad)

  W.assign_sub(W_grad * learning_rate)
  b.assign_sub(b_grad * learning_rate)

  print("=" * 100)

hypothesis: tf.Tensor([1.9166656 2.6666665 3.4166672], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013888902, shape=(), dtype=float32)
W_grad: tf.Tensor([1.6391277e-07], shape=(1,), dtype=float32) , b_grad: tf.Tensor([-4.7683716e-07], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([1.9166656 2.6666665 3.4166672], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013888902, shape=(), dtype=float32)
W_grad: tf.Tensor([1.6391277e-07], shape=(1,), dtype=float32) , b_grad: tf.Tensor([-4.7683716e-07], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([1.9166656 2.6666665 3.4166672], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013888902, shape=(), dtype=float32)
W_grad: tf.Tensor([1.6391277e-07], shape=(1,), dtype=float32) , b_grad: tf.Tensor([-4.7683716e-07], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([1.9166656 2.6666665 3.4166672], shape=(3,), dtype=float32)
cost: tf.Tensor(0.013888902, shape=(), dtype=float32)
W_grad: tf.Tensor([1.6391277e-07], shape=(1,), dtype=float32) , b_grad: tf.

In [60]:
X * W + b

<tf.Tensor: id=78485, shape=(3,), dtype=float32, numpy=array([1.4333333, 2.3333333, 3.233333 ], dtype=float32)>

In [62]:
Y

array([2. , 2.5, 3.5], dtype=float32)

In [63]:
10 * W + b

<tf.Tensor: id=78490, shape=(1,), dtype=float32, numpy=array([9.533333], dtype=float32)>

In [64]:
20 * W + b

<tf.Tensor: id=78495, shape=(1,), dtype=float32, numpy=array([18.533333], dtype=float32)>