<a href="https://colab.research.google.com/github/nojiyoon/SeSAC_code/blob/main/3_5_%EC%9D%B8%EA%B3%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%84_%EC%9D%B4%EC%9A%A9%ED%95%9C_AND%EC%97%B0%EC%82%B0(%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_2_x).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

In [3]:
import numpy as np

In [4]:
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
])

In [5]:
y = np.array([
      [0],
      [0],
      [0],
      [1], 
])

In [6]:
from tensorflow.keras.models import Sequential

In [7]:
model = Sequential()

In [8]:
from tensorflow.keras.layers import Dense

In [9]:
model.add(Dense(1, input_dim=2, activation='sigmoid'))

In [10]:
# w, b의 초기값
model.layers[0].get_weights()

[array([[ 1.3036374],
        [-0.7623104]], dtype=float32), array([0.], dtype=float32)]

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [13]:
from tensorflow.keras.optimizers import Adam

In [14]:
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc'])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [15]:
model.fit(X, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 0.7697 - acc: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7285 - acc: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6906 - acc: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 23ms/step - loss: 0.6561 - acc: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6253 - acc: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 0.5980 - acc: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 21ms/step - loss: 0.5742 - acc: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 17ms/step - loss: 0.5536 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 12ms/step - loss: 0.5356 - acc: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 0.5195 - acc: 0.7500
Epoch 11/100
1/1 [==============================] - 0s 11ms/step - loss:

In [17]:
pred = model.predict(X)
pred

array([[0.00325152],
       [0.12606809],
       [0.120502  ],
       [0.85833275]], dtype=float32)

In [18]:
predict01 = np.where(pred>=0.5, 1, 0)
predict01

array([[0],
       [0],
       [0],
       [1]])

In [19]:
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [20]:
predict03 = (predict02 == y)
predict03

array([[ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True, False],
       [False, False, False,  True]])

In [21]:
np.sum(predict03)

10

In [22]:
acc = np.sum(predict03) / 4
acc

2.5