<a href="https://colab.research.google.com/github/nojiyoon/SeSAC_code/blob/main/6_3_%EC%8B%AC%EC%B8%B5_%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%84_%EC%9D%B4%EC%9A%A9%ED%95%9C_XOR_(%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_2_x).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [24]:
# XOR 연산의 x1, x2 입력을 저장하는 배열
X = np.array([
              [0., 0.],
              [0., 1.],
              [1., 0.],
              [1., 1.]
        ], dtype = 'float32')

# XOR 연산의 y출력을 저장하는 배열
y = np.array( [0,1,1,0], dtype="float32")

In [25]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [26]:
y

array([0., 1., 1., 0.], dtype=float32)

In [27]:
model = Sequential()

In [28]:
model.add(Dense(2, input_dim=2, activation='sigmoid'))

In [29]:
model.add(Dense(1, activation='sigmoid'))

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [31]:
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.01), metrics=['acc'])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [32]:
model.fit(X, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 372ms/step - loss: 0.7222 - acc: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7195 - acc: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7169 - acc: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7145 - acc: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7123 - acc: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7102 - acc: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7083 - acc: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7065 - acc: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 11ms/step - loss: 0.7050 - acc: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7035 - acc: 0.5000
Epoch 11/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7

In [33]:
pred = model.predict(X)

In [34]:
pred

array([[0.10436706],
       [0.87916666],
       [0.90059215],
       [0.09040355]], dtype=float32)

In [36]:
predict01 = np.where(pred>0.5, 1, 0)
print("=========================")
print("predict01")
print(predict01)

predict01
[[0]
 [1]
 [1]
 [0]]


In [37]:
predict02 = predict01.flatten()
predict02

array([0, 1, 1, 0])

In [38]:
predict03 = (predict02 == y)
predict03

array([ True,  True,  True,  True])

In [39]:
np.sum(predict03)

4

In [40]:
acc = np.sum(predict03) / len(predict03)
acc

1.0

In [41]:
arr = np.array([[0,1]], dtype="float32")
pred=model.predict(arr)
pred

array([[0.87916666]], dtype=float32)

In [42]:
predict01 = np.where(pred>0.5, 1, 0)
print("==================")
print("predict01")
print(predict01)

predict01
[[1]]


In [43]:
arr = np.array([[1,1]], dtype="float32")
pred=model.predict(arr)
pred

array([[0.09040355]], dtype=float32)

In [44]:
predict01 = np.where(pred>0.5, 1, 0)
print("==================")
print("predict01")
print(predict01)

predict01
[[0]]
