<a href="https://colab.research.google.com/github/nojiyoon/SeSAC_code/blob/main/7_1_%EC%8B%AC%EC%B8%B5_%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%84_%EC%9D%B4%EC%9A%A9%ED%95%9C_%EC%9C%A0%EB%B0%A9%EC%95%94_%EB%B6%84%EB%A5%98_(%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_1_x).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.nn import relu
import tensorflow as tf
tf.enable_eager_execution()

In [3]:
data = datasets.load_breast_cancer()
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.

In [4]:
X = data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
X = np.array(X, dtype='float32')
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [6]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
y = np.array(y, dtype="float32")
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [8]:
y = y.reshape(-1, 1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
X_train

array([[1.097e+01, 1.720e+01, 7.173e+01, ..., 1.555e-01, 2.540e-01,
        9.532e-02],
       [2.058e+01, 2.214e+01, 1.347e+02, ..., 1.920e-01, 2.909e-01,
        5.865e-02],
       [1.240e+01, 1.768e+01, 8.147e+01, ..., 7.370e-02, 2.556e-01,
        9.359e-02],
       ...,
       [1.327e+01, 1.476e+01, 8.474e+01, ..., 1.001e-01, 2.027e-01,
        6.206e-02],
       [8.571e+00, 1.310e+01, 5.453e+01, ..., 8.512e-02, 2.983e-01,
        1.049e-01],
       [1.366e+01, 1.515e+01, 8.827e+01, ..., 1.054e-01, 3.387e-01,
        9.638e-02]], dtype=float32)

In [11]:
X_test

array([[1.422e+01, 2.785e+01, 9.255e+01, ..., 8.219e-02, 1.890e-01,
        7.796e-02],
       [1.616e+01, 2.154e+01, 1.062e+02, ..., 1.312e-01, 3.480e-01,
        7.619e-02],
       [1.242e+01, 1.504e+01, 7.861e+01, ..., 4.052e-02, 2.901e-01,
        6.783e-02],
       ...,
       [1.334e+01, 1.586e+01, 8.649e+01, ..., 1.708e-01, 3.527e-01,
        1.016e-01],
       [1.411e+01, 1.288e+01, 9.003e+01, ..., 5.890e-02, 2.100e-01,
        7.083e-02],
       [1.550e+01, 2.108e+01, 1.029e+02, ..., 2.134e-01, 3.003e-01,
        1.048e-01]], dtype=float32)

In [12]:
y_train

array([[1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],

In [13]:
y_test

array([[1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train=scaler.transform(X_train)
X_train

array([[-0.8609151 , -0.50310576, -0.7997275 , ...,  0.6629398 ,
        -0.5869238 ,  0.62374014],
       [ 1.8647344 ,  0.6606716 ,  1.7909002 , ...,  1.2334489 ,
        -0.00196514, -1.3860801 ],
       [-0.45532954, -0.3900262 , -0.3990174 , ..., -0.6156254 ,
        -0.56155974,  0.5289216 ],
       ...,
       [-0.20857435, -1.0779271 , -0.26448756, ..., -0.20298328,
        -1.4001594 , -1.1991838 ],
       [-1.5413347 , -1.4689941 , -1.5073472 , ..., -0.43712643,
         0.11534379,  1.1488036 ],
       [-0.09796023, -0.9860501 , -0.11926106, ..., -0.12014224,
         0.7557866 ,  0.68183696]], dtype=float32)

In [17]:
# w와 b를 초기화시키는 객체를 생성
initializer = tf.contrib.layers.xavier_initializer()

w0 = tf.Variable(initializer([30,30]))
w0

<tf.Variable 'Variable:0' shape=(30, 30) dtype=float32, numpy=
array([[-2.94516027e-01,  2.79399306e-01, -2.32363820e-01,
        -1.07893631e-01,  2.60085016e-01, -3.63983810e-02,
         1.46173507e-01,  2.84106433e-02,  2.32243240e-02,
        -2.98132539e-01,  3.85828018e-02, -9.74856317e-02,
        -2.67341256e-01,  1.90363735e-01,  2.89259285e-01,
         2.20754176e-01, -2.81498998e-01, -1.46974564e-01,
         2.55537063e-01,  2.30297774e-01, -1.55489147e-02,
         2.28589386e-01, -3.05969894e-01,  1.10333771e-01,
         2.95631289e-02,  1.91828460e-01,  2.85996288e-01,
         2.00275987e-01,  1.09273195e-01, -2.75082529e-01],
       [ 7.27480054e-02, -1.90839797e-01,  1.21671915e-01,
         6.14120364e-02, -3.23185623e-02, -3.71688604e-03,
         7.97007978e-02, -9.65202898e-02, -8.85646492e-02,
        -2.03529462e-01, -1.71332732e-01,  2.91122586e-01,
         3.30086350e-02, -2.80479729e-01, -1.18928760e-01,
        -1.03495792e-01, -2.25432426e-01, -2.265460

In [18]:
#tf.Variable(initializer([30])) : 30줄 1칸의 b0을 생성해서 리턴
b0 = tf.Variable(initializer([30])) 
b0

<tf.Variable 'Variable:0' shape=(30,) dtype=float32, numpy=
array([ 0.31194326, -0.20888495, -0.09882382,  0.31570885, -0.09088786,
        0.06097627,  0.23949054,  0.1099771 , -0.05449361, -0.00855124,
       -0.28472987, -0.10071698,  0.1602186 ,  0.26464316, -0.21272638,
        0.23626217,  0.12787974,  0.06923214,  0.04982555,  0.266817  ,
        0.03106618,  0.13946623, -0.11198673,  0.01593268,  0.05483213,
       -0.12285048, -0.00110197, -0.01129901, -0.10997233,  0.16140899],
      dtype=float32)>

In [19]:
w1 = tf.Variable(initializer([30,10])) 
w1

<tf.Variable 'Variable:0' shape=(30, 10) dtype=float32, numpy=
array([[-0.12149817, -0.3799802 , -0.27624154, -0.10864881, -0.28195143,
        -0.0744701 ,  0.36676508,  0.15007073, -0.3859333 ,  0.38448143],
       [-0.0271295 , -0.2954995 ,  0.2518496 , -0.3668504 , -0.2668177 ,
        -0.31269866, -0.0239681 , -0.0662187 , -0.36898288, -0.33602992],
       [-0.10182503, -0.2817176 , -0.1475015 ,  0.11617029,  0.3770305 ,
        -0.3543934 ,  0.08714375,  0.09579086,  0.34641862, -0.04250666],
       [ 0.14624345, -0.08093357, -0.07267043,  0.11661941, -0.31813672,
         0.26432353, -0.17221431,  0.08649987, -0.05510929,  0.01642585],
       [ 0.33252   ,  0.18243366,  0.27297598, -0.36743554,  0.29168707,
        -0.13001117, -0.2479176 ,  0.38710803, -0.13924232, -0.08865941],
       [-0.18868724, -0.10632417,  0.14866   ,  0.35907102,  0.03517899,
        -0.33436504, -0.05362704,  0.0304589 ,  0.16523516,  0.37409616],
       [-0.2955213 , -0.30086154, -0.17008561, -0.06098

In [20]:
b1 = tf.Variable(initializer([10])) 
b1

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([ 0.30310237,  0.2180525 , -0.11688328,  0.5181006 ,  0.01625979,
       -0.01305896, -0.23271456, -0.1600284 ,  0.52710235,  0.09789997],
      dtype=float32)>

In [21]:
w2 = tf.Variable(initializer([10,1]))
w2 

<tf.Variable 'Variable:0' shape=(10, 1) dtype=float32, numpy=
array([[-0.461277  ],
       [-0.488483  ],
       [ 0.2970292 ],
       [ 0.06993663],
       [-0.17064613],
       [-0.5558412 ],
       [-0.62844443],
       [ 0.6016801 ],
       [-0.08830708],
       [ 0.11562365]], dtype=float32)>

In [22]:
b2 = tf.Variable(initializer([1]))
b2

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.7434002], dtype=float32)>

In [23]:
tf.matmul(X_train, w0) + b0

<tf.Tensor: id=95, shape=(455, 30), dtype=float32, numpy=
array([[-5.5059046e-02,  6.4823031e-04, -8.8420248e-01, ...,
        -4.3333161e-01, -9.7898945e-02,  8.3176923e-01],
       [-4.9228528e-01,  1.5628077e+00, -6.5791404e-01, ...,
         2.4902582e-01,  3.4012502e-01,  1.0983013e+00],
       [ 3.4688315e-01, -3.3194864e-01, -4.1724676e-01, ...,
        -1.7062736e-01, -1.8495192e-01, -2.2048992e-01],
       ...,
       [-3.5069749e-01,  7.8622311e-02,  2.9296499e-01, ...,
         1.4144137e+00,  4.3502828e-01,  1.1260890e+00],
       [ 3.4512582e-01, -1.3385835e+00,  2.3216790e-01, ...,
        -1.0360500e-02, -6.2207663e-01, -8.4308755e-01],
       [ 7.9693383e-01, -1.0891473e+00, -1.4203851e-01, ...,
        -1.7059559e-02, -7.6537323e-01, -8.3654594e-01]], dtype=float32)>

In [24]:
hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
hypothesis0

<tf.Tensor: id=101, shape=(455, 30), dtype=float32, numpy=
array([[0.48623872, 0.50016207, 0.29230767, ..., 0.39333108, 0.4755448 ,
        0.6967289 ],
       [0.37935537, 0.8267559 , 0.34120837, ..., 0.5619367 , 0.5842209 ,
        0.7499417 ],
       [0.58586156, 0.41776657, 0.3971758 , ..., 0.45744637, 0.4538934 ,
        0.44509977],
       ...,
       [0.4132133 , 0.51964545, 0.57272184, ..., 0.8044611 , 0.6070737 ,
        0.75511634],
       [0.5854351 , 0.20774311, 0.55778265, ..., 0.4974099 , 0.34930933,
        0.3008849 ],
       [0.6893182 , 0.2517789 , 0.46454996, ..., 0.49573523, 0.31748083,
        0.30226275]], dtype=float32)>

In [25]:
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
hypothesis1

<tf.Tensor: id=106, shape=(455, 10), dtype=float32, numpy=
array([[0.61955106, 0.57406056, 0.4550243 , ..., 0.67682034, 0.52698845,
        0.35834247],
       [0.6312882 , 0.5295517 , 0.48823652, ..., 0.68344057, 0.63246256,
        0.37555426],
       [0.6315071 , 0.5458374 , 0.45191517, ..., 0.7056027 , 0.5693876 ,
        0.40941283],
       ...,
       [0.6486206 , 0.48081285, 0.5833682 , ..., 0.6372447 , 0.655843  ,
        0.43953878],
       [0.6450718 , 0.5368226 , 0.4760857 , ..., 0.6719997 , 0.60096496,
        0.4348912 ],
       [0.6427499 , 0.5461239 , 0.5246753 , ..., 0.68274075, 0.61815846,
        0.44070536]], dtype=float32)>

In [29]:
hypothesis2 = tf.sigmoid(tf.matmul(hypothesis1, w2) + b2)
hypothesis2

<tf.Tensor: id=130, shape=(455, 1), dtype=float32, numpy=
array([[0.18144357],
       [0.19181418],
       [0.17673653],
       [0.11941296],
       [0.1510024 ],
       [0.16755986],
       [0.22928578],
       [0.27371663],
       [0.18074375],
       [0.13900092],
       [0.18522784],
       [0.18289077],
       [0.13972858],
       [0.17373031],
       [0.15059757],
       [0.22852412],
       [0.24211702],
       [0.16412318],
       [0.19838113],
       [0.19861498],
       [0.13831055],
       [0.17132378],
       [0.16106346],
       [0.1593748 ],
       [0.15372285],
       [0.20459136],
       [0.13918558],
       [0.27834728],
       [0.16751316],
       [0.2047557 ],
       [0.1312466 ],
       [0.14043134],
       [0.1616917 ],
       [0.18321359],
       [0.12375665],
       [0.11308482],
       [0.11827058],
       [0.18082109],
       [0.17026675],
       [0.13735953],
       [0.26737544],
       [0.17815149],
       [0.17756078],
       [0.12784472],
       [0.25119597

In [27]:
optimizer = tf.train.AdamOptimizer(0.01)

In [32]:
for step in range(1001):
  with tf.GradientTape() as tape:
    hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0)+b0)
    hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1)+b1)
    hypothesis2 = tf.sigmoid(tf.matmul(hypothesis1, w2)+b2)

    cost = -tf.reduce_mean(y_train * tf.log(hypothesis2) + (1 - y_train) * tf.log(1 - hypothesis2))
    grads = tape.gradient(cost, [w0, w1, w2, b0, b1, b2])

    optimizer.apply_gradients(grads_and_vars=zip(grads,[w0,w1,w2,b0,b1,b2]))

    if step % 100 == 0:
      print("="*50)
      print("step: {}, cost: {}".format(step, cost.numpy()))
      print("=" * 50)

step: 0, cost: 1.0380843877792358
step: 100, cost: 0.06501302868127823
step: 200, cost: 0.035121094435453415
step: 300, cost: 0.026635386049747467
step: 400, cost: 0.010997497476637363
step: 500, cost: 0.005154560785740614
step: 600, cost: 0.003130691358819604
step: 700, cost: 0.0021645959932357073
step: 800, cost: 0.0016135239275172353
step: 900, cost: 0.0012625458184629679
step: 1000, cost: 0.001021740259602666


In [33]:
w0

<tf.Variable 'Variable:0' shape=(30, 30) dtype=float32, numpy=
array([[-6.82646036e-01, -1.08853709e-02, -4.23566490e-01,
        -4.10577327e-01, -1.39131630e-02, -2.42621362e-01,
        -1.22761920e-01, -4.84965354e-01, -9.27885622e-03,
        -3.87719095e-01, -1.93816960e-01, -3.30970377e-01,
        -4.31316912e-01,  2.06972077e-01,  2.52116442e-01,
         7.16724217e-01, -6.65542603e-01,  1.18254282e-01,
         2.93540239e-01, -1.36220083e-01, -2.14521550e-02,
         1.97713733e-01, -5.95033944e-01,  3.32275242e-01,
        -1.04766309e-01,  7.52452984e-02, -1.84340298e-01,
        -4.52906899e-02, -1.23911150e-01, -5.99373400e-01],
       [-3.99939567e-02, -8.75598252e-01,  3.26514930e-01,
         1.41989827e-01, -5.18252887e-02, -2.00877547e-01,
        -2.30932891e-01,  5.85896038e-02, -3.94935727e-01,
        -7.75052607e-01,  6.24835551e-01,  4.70882058e-01,
         6.64000213e-02,  5.15598476e-01, -5.52682161e-01,
        -1.97313571e+00,  3.01290989e-01, -4.379425

In [34]:
b0

<tf.Variable 'Variable:0' shape=(30,) dtype=float32, numpy=
array([ 0.5378868 , -0.7131008 , -0.22741453,  0.26334757, -0.13160071,
       -0.18599176, -0.06474886,  0.63152826, -0.8033238 , -0.5272271 ,
       -0.6665146 , -0.40238467, -0.5683437 , -0.09625284,  0.591051  ,
        0.40961254,  0.1720279 , -0.379988  , -0.06827634,  0.976431  ,
        0.0209913 , -0.24885689, -1.4239149 , -0.08191922, -0.5467857 ,
       -0.31341684, -0.30021465, -0.43678135, -0.4859721 ,  0.56553376],
      dtype=float32)>

In [35]:
w1

<tf.Variable 'Variable:0' shape=(30, 10) dtype=float32, numpy=
array([[-0.44576728, -0.6444605 ,  0.13763094,  0.15642244, -0.50362235,
        -0.2579385 ,  0.18133564,  0.36390206,  0.01596927,  0.6244571 ],
       [-0.3990836 , -0.6525529 ,  0.6247748 ,  0.16811758, -0.7788912 ,
        -0.6528561 , -0.34960967,  0.23772562,  0.3881745 ,  0.19840771],
       [-0.37490368, -0.5519056 ,  0.16736628,  0.51786613, -0.05492438,
        -0.58406156, -0.18925282,  0.35747015,  0.62370723,  0.45103258],
       [-0.18731877, -0.37487197,  0.31436738,  0.42886958, -0.5642826 ,
         0.0360948 , -0.40354806,  0.33606878,  0.32066637,  0.3576133 ],
       [-0.14046909, -0.30270046,  0.7591866 ,  0.6026042 , -0.60370904,
        -0.58019894, -0.6778361 ,  0.8119094 ,  0.86916703,  0.66413265],
       [-0.47826344, -0.3820842 ,  0.43395033,  0.7610141 , -0.2954509 ,
        -0.5859474 , -0.30121633,  0.27438298,  0.44553772,  0.79747146],
       [-0.57359505, -0.5530294 ,  0.07989002,  0.24388

In [36]:
b1

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([ 0.4279443 ,  0.42316902, -0.41100276, -0.16016905,  0.49070123,
        0.24320476,  0.05059915, -0.5168699 ,  0.26892704, -0.44843832],
      dtype=float32)>

In [37]:
w2

<tf.Variable 'Variable:0' shape=(10, 1) dtype=float32, numpy=
array([[-1.1391184],
       [-1.445749 ],
       [ 1.6654671],
       [ 1.3673592],
       [-1.6105026],
       [-1.6326926],
       [-1.7636552],
       [ 1.8004764],
       [ 1.108772 ],
       [ 1.5751508]], dtype=float32)>

In [38]:
b2

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.09455226], dtype=float32)>

In [39]:
X_test = scaler.transform(X_test)
X_test

array([[ 0.06087066,  2.005848  ,  0.05682127, ..., -0.48292348,
        -1.6173394 , -0.32773194],
       [ 0.6111057 ,  0.51932245,  0.61839116, ...,  0.2831216 ,
         0.9032151 , -0.42474246],
       [-0.44965687, -1.0119641 , -0.51667976, ..., -1.1342415 ,
        -0.01464692, -0.8829401 ],
       ...,
       [-0.18872058, -0.81878656, -0.1924914 , ...,  0.9020847 ,
         0.97772217,  0.96793604],
       [ 0.02967159, -1.5208223 , -0.04685339, ..., -0.84695506,
        -1.284436  , -0.7185149 ],
       [ 0.42391238,  0.4109543 ,  0.48262715, ...,  1.567939  ,
         0.14704894,  1.1433227 ]], dtype=float32)

In [41]:
hypothesis0 = tf.sigmoid(tf.matmul(X_test, w0)+b0)
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1)+b1)
predict = tf.sigmoid(tf.matmul(hypothesis1, w2)+b2)

predict

<tf.Tensor: id=103433, shape=(114, 1), dtype=float32, numpy=
array([[6.6105366e-01],
       [4.7823787e-04],
       [9.9939322e-01],
       [9.9937499e-01],
       [9.9933368e-01],
       [1.4746785e-03],
       [9.9932516e-01],
       [5.8481097e-04],
       [4.7186017e-04],
       [9.9936736e-01],
       [9.9939990e-01],
       [9.9939990e-01],
       [4.7352910e-04],
       [9.9935865e-01],
       [9.9930537e-01],
       [9.9939072e-01],
       [9.9909425e-01],
       [4.7445297e-04],
       [7.5680017e-04],
       [5.7247281e-04],
       [4.7191978e-04],
       [4.8100948e-04],
       [9.9939680e-01],
       [9.9939907e-01],
       [4.7346950e-04],
       [7.0247054e-04],
       [4.7242641e-04],
       [4.7323108e-04],
       [4.7206879e-04],
       [9.9926734e-01],
       [7.4511445e-01],
       [9.9939704e-01],
       [9.7328424e-04],
       [9.9938655e-01],
       [9.9938411e-01],
       [9.6201897e-01],
       [9.9937660e-01],
       [4.7147274e-04],
       [5.0279498e-04],
   

In [42]:
predict01 = tf.cast(predict > 0.5, dtype=tf.float32)
predict01

<tf.Tensor: id=103436, shape=(114, 1), dtype=float32, numpy=
array([[1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
   

In [43]:
ac01 = tf.equal(predict01, y_test)
ac01

<tf.Tensor: id=103438, shape=(114, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]

In [44]:
ac02 = tf.cast(ac01, dtype="float32")
ac02

<tf.Tensor: id=103439, shape=(114, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
   

In [45]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=103441, shape=(), dtype=float32, numpy=0.9649123>

In [46]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y_test), dtype=tf.float32))
accuracy.numpy()

0.9649123